[build]
  publish = "."
  command = "npm install"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/upload/*"
  to = "/.netlify/functions/upload/:splat"
  status = 200
